### PR TITLE
Track all errors thrown by Coral Talk

### PR DESCRIPTION
**Pull request by ker-an**
Recently, we came across an issue where users were unable comment due to
some internal error on Coral's side. The issue was reported by different
users.

This PR allows us to track any errors and spot issues before it's
reported by users.

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-comments bundle size difference from 7.4.1 to 6edbdc01a6b49fe250152cc68af3634319b743d2
No significant bundle size differences found.

**Comment by JakeChampion** [comment]
Is this PR still applicable?

**Comment by ker-an** [comment]
@JakeChampion I want to say yes but let me confirm.

**Comment by origamiserviceuser** [comment]
o-comments bundle size difference from 7.4.2 to 79d94f6e1bf733126ff903cb39c8d22d0ef25870
No significant bundle size differences found.

**Comment by notlee** [comment]
Hey comments team! Jake built a cool Github action which allows us to release o-things by adding a label and merging 🎉 `release:major`, `release:minor`, `release:patch`

Just a heads up, the original flow for releasing is still good 😊

**Comment by ker-an** [comment]
@notlee Damn that is so cool! I wish I had known earlier!

**Comment by notlee** [comment]
@ker-an it's very new and sometimes I forget still. It's like "WHAT I'M SUPPOSED TO FIGURE OUT THE VERSION MYSELF AND WRITE THE TAG LIKE SOME KIND OF ANIMAL!?"

**Pull request merged**
