### PR TITLE
Update readme to conform to the readme linter

### PR DESCRIPTION
**Pull request by chee**
please forgive me

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-comments bundle size difference from 7.6.7 to ef045b34ddc8cfc6c60f35e750f28ffde1316c39
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comments bundle size difference from 7.6.7 to d0c4c22a4ed3f5f193143ea096b9809593e5d221
No significant bundle size differences found.

**Comment by chee** [comment]
@Financial-Times/content-innovation is this ok to merge in?

**Comment by origamiserviceuser** [comment]
o-comments bundle size difference from 7.6.7 to 1dcf71bb171997bbae37dbc2fd1f6a65f5ef67dd
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v7.7.1 :tada:

**Pull request merged**
