### PR TITLE
Update the required parameters for initialisation and update the docs

### PR DESCRIPTION
**Pull request by rowanbeentje**
o-comments currently outputs console errors if required parameters are not used during initialisation, added in https://github.com/Financial-Times/o-comments/commit/7515a0d3715d3eac0bb9b375747f90b648779361 as a result of a discussion in https://github.com/Financial-Times/o-comments/issues/27 . However these fields date back to the original LiveFyre implementation; with the move to CoralTalk, `title` is no longer used, and `articleUrl` is now optional. I've removed the console errors, and tried to add some documentation explaining what I think the remaining parameters are for...

(There may be some old implementations still supplying a title. I don't think it's worth adding a warning/info/anything saying that can now be removed, but maybe it's worth it?)

### CODE REVIEW

**Comment by rowanbeentje** [comment]
@GlynnPhillips or @Financial-Times/content-innovation any thoughts? If I don't hear otherwise I'll merge this later today 😁

**Review by GlynnPhillips — APPROVED** [review]
Sorry @rowanbeentje I missed this PR coming in :) All looks good thanks for taking care of it

**Comment by rowanbeentje** [comment]
And thanks jake for fixing `obt`-flagged issues! 😁

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v8.1.1 :tada:

**Pull request merged**
